apiVersion: v1
data:
  database-address: "{{ db_address }}"
  database-name: "{{ db_name }}"
  database-port: "{{ db_port }}"
kind: ConfigMap
metadata:
  name: revolut-app-config
  namespace: default
