apiVersion: v1
data:
  database-password: "{{ db_address | b64encode }}"
  database-username: "{{ db_username | b64encode }}"
kind: Secret
metadata:
  name: revolut-app-secrets
  namespace: default
type: Opaque
