apiVersion: v1
kind: Service
metadata:
  name: revolut-app
  namespace: default
  labels:
    app: revolut-app
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: revolut-app
  type: LoadBalancer
